### ISSUE TITLE
playback.php

### ISSUE THREAD

**Issue by Bardo-Konrad** [luileito/evtrack#1]
Can you offer a playback.php aswell?

**Comment by luileito** [comment]
Unfortunately not. A PR for this would be welcome, though.

**Comment by Bardo-Konrad** [comment]
What do you need to create the file that plays it back?
What is a PR?

**Comment by luileito** [comment]
For playback you need to implement a lot of features that go beyond the purpose and scope of this software. See e.g. https://github.com/luileito/smt2 for an _old_ implementation of a fully-fledged mouse tracking system and [this paper](https://luis.leiva.name/web/docs/papers/smt2-www2012-preprint.pdf) for an overview of some of the desired features and a few implementation details. It took me several years to develop such system in my spare time, and still there are many things to improve there, but unfortunately I don't have time to revisit that system anymore.

A PR is a pull request. It is the way that external github users have to contribute to other people's repositories. See https://help.github.com/en/articles/about-pull-requests
